
# Nombre de la aplicación
spring.application.name=perfumeria-backend

# Puerto del servidor backend
server.port=8080

# Configuración de Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/perfumeria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración del Pool de Conexiones (Hikari)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.max-lifetime=1800000

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Stripe
stripe.secret.key=TU_SECRET_KEY
stripe.public.key=TU_PUBLIC_KEY